### ISSUE TITLE
Prepare Zzz Spoon for Publication

### ISSUE THREAD

**Issue by nonissue** [nonissue/hammerspoon#21]
### Tasks

- [x] Cleanup code
- [x] Ensure all Spoons conform to suggested practices (eg. use `bindHotkeys`)
- [x] Add conformant documentation
- [x] Add necessary code comments
- [x] Verify spoons work on clean install without issue

**Comment by nonissue** [comment]
Prep done.
